#!/bin/sh


unset GIT_WORK_TREE
unset GIT_DIR
unset GIT_INDEX_FILE

mkdir a

GEN_DIR=~/TestDox
echo "Going to ${GEN_DIR}"
cd "${GEN_DIR}"
echo "Getting changes"
git pull -f

echo "Generating documentation"
cd hw11
mkdir a
doxygen doxygen.config > /dev/null